source 'https://rubygems.org'
ruby '>= 3.4', '< 5.0'
gem 'feedjira', '~>3.0'
gem 'ginseng-core', github: 'pooza/ginseng-core', branch: 'main', require: 'ginseng'
gem 'ginseng-fediverse', github: 'pooza/ginseng-fediverse', branch: 'main', require: 'ginseng/fediverse'
gem 'ginseng-piefed', github: 'pooza/ginseng-piefed', branch: 'main', require: 'ginseng/piefed'
gem 'ginseng-youtube', github: 'pooza/ginseng-youtube', branch: 'main', require: 'ginseng/you_tube'
gem 'icalendar'
gem 'icalendar-rrule', github: 'pooza/icalendar-rrule',
  ref: '396a2c3e6b5cf394c2416f39c05e948cccd4ea52'
gem 'nostr'
gem 'optparse'
gem 'parallel'
gem 'rufus-scheduler'
gem 'sentry-ruby'
gem 'sequel'
gem 'sqlite3'

group :development do
  gem 'ricecream'
  gem 'rubocop'
  gem 'rubocop-minitest'
  gem 'rubocop-performance'
  gem 'rubocop-rake'
  gem 'rubocop-sequel'
  gem 'test-unit'
end
