source 'https://rubygems.org'
ruby '~>3.4.0'
gem 'feedjira', '~>3.0'
gem 'ginseng-core', github: 'pooza/ginseng-core', require: 'ginseng'
gem 'ginseng-fediverse', github: 'pooza/ginseng-fediverse', require: 'ginseng/fediverse'
gem 'ginseng-youtube', github: 'pooza/ginseng-youtube', require: 'ginseng/youtube'
gem 'icalendar'
gem 'icalendar-rrule'
gem 'optparse'
gem 'rufus-scheduler'
gem 'sequel'
gem 'sqlite3'

group :development do
  gem 'ricecream'
  gem 'rubocop'
  gem 'rubocop-minitest'
  gem 'rubocop-performance'
  gem 'rubocop-rake'
  gem 'rubocop-sequel'
  gem 'test-unit'
end
