source 'https://rubygems.org'
ruby '~>3.1.0'
gem 'bootsnap', '>=1.9.0'
gem 'faye-websocket', github: 'pooza/faye-websocket-ruby'
gem 'feedjira', '~>3.0'
gem 'ginseng-core', github: 'pooza/ginseng-core', require: 'ginseng'
gem 'ginseng-fediverse', github: 'pooza/ginseng-fediverse', require: 'ginseng/fediverse'
gem 'optparse'
gem 'rufus-scheduler'
gem 'sequel'
gem 'sqlite3'

group :development do
  gem 'ricecream'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rake'
  gem 'rubocop-sequel'
  gem 'test-unit'
end
