#!/bin/sh

# PROVIDE: tomato-shrieker
# REQUIRE: LOGIN

# Add the following line to /etc/rc.conf to enable `tomato-shrieker':
#
#tomato_shrieker_enable="YES"

. /etc/rc.subr

name="tomato_shrieker"
rcvar="${name}_enable"

load_rc_config "$name"
: ${tomato_shrieker_enable="NO"}
: ${tomato_shrieker_path=""}
: ${tomato_shrieker_user=""}

export PATH=${PATH}:/usr/local/bin:/usr/local/sbin
export LANG=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8

start_cmd=${name}_start
stop_cmd=${name}_stop

tomato_shrieker_start() {
  cd $tomato_shrieker_path
  sudo -u $tomato_shrieker_user /bin/bash -lc 'bundle exec rake start'
}

tomato_shrieker_stop() {
  cd $tomato_shrieker_path
  sudo -u $tomato_shrieker_user /bin/bash -lc 'bundle exec rake stop'
}

run_rc_command "$1"
