---
$schema: http://json-schema.org/draft-04/hyper-schema
properties:
  crypt:
    properties:
      password:
        type: string
    required:
      - password
  disable:
    type: boolean
  environment:
    enum:
      - development
      - production
    type: string
  feed:
    properties:
      default_tags:
        items:
          type: string
        type: array
    type: object
  slack:
    properties:
      hooks:
        items:
          format: url
          type: string
        type: array
    required:
      - hooks
    type: object
  sources:
    items:
      properties:
        dest:
          properties:
            dest:
              account:
                properties:
                  bot:
                    type: boolean
                type: hash
              category:
                type: string
              hooks:
                items:
                  format: url
                  type: string
                type: array
              line:
                properties:
                  token:
                    type: string
                  user_id:
                    type: string
                required:
                  - user_id
                  - token
                type: hash
              mastodon:
                properties:
                  token:
                    type: string
                  url:
                    format: url
                    type: string
                required:
                  - url
                  - token
                type: hash
              misskey:
                properties:
                  token:
                    type: string
                  url:
                    format: url
                    type: string
                required:
                  - url
                  - token
                type: hash
              multi_entries:
                type: boolean
              mulukhiya:
                properties:
                  enable: boolean
                required:
                  - enable
                type: hash
              piefed:
                properties:
                  community_id:
                    type: integer
                  host:
                    type: string
                  password:
                    type: string
                  template:
                    type: string
                  user_id:
                    type: string
                required:
                  - host
                  - user_id
                  - password
                  - comunity_id
                type: hash
              prefix:
                type: string
              spoiler_text:
                type: string
              tags:
                items:
                  type: string
                type: array
              template:
                type: string
              visibility: string
          type: hash
        id:
          type: string
        schedule:
          properties:
            at:
              type: string
            cron:
              type: string
            every:
              type: string
          type: hash
        source:
          properties:
            calendar:
              format: url
              type: string
            command:
              items:
                type: string
              type:
                - array
            days:
              type: integer
            delimiter:
              type: string
            dir:
              type: string
            env:
              type: hash
            feed:
              format: url
              type: string
            github:
              format: hash
              properties:
                repos:
                  type: string
                repository:
                  type: string
                timeline:
                  enum:
                    - releases
                    - commits
                  type: string
            ical:
              format: url
              type: string
            keyword:
              type: string
            negative_keyword:
              type: string
            news:
              format: hash
              properties:
                phrase:
                  type: string
                url:
                  format: url
                  type: string
            text:
              type: string
            title:
              properties:
                unique:
                  type: boolean
              type: hash
            url:
              format: url
              type: string
          type: hash
      required:
        - source
        - dest
      type: object
    type: array
required:
  - environment
  - crypt
title: Local config
type: object
