name: test
on:
  - push
env:
  CI: 'true'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0'
      - name: apt install
        run: |
          sudo apt update
          sudo apt install libsqlite3-dev
      - name: prepare config
        run: cp config/local_sample.yaml config/local.yaml
      - name: bundle install
        run: |
          gem install bundler -v '~>4.0'
          bundle install --jobs 4 --retry 3
          bundle exec rake bundle:update
          git diff
          bundle exec rake bundle:check
      - run: bundle exec rake migration:run
      - run: bundle exec rubocop
      - run: bundle exec rake config:lint
      - run: bundle exec rake test
